<?php
    $categories = $this->getCategoryCollection();
    $categoryHelper = $this->getCategoryHelper();
?>
<div class="widget block block-static-block">
    <div class="block-content">
        <div class="row">
        <?php
        foreach($categories as $category):
            $cat = $this->getCategorymodel($category->getId());
            $image = $cat->getImageUrl();
        ?>
            <?php if($image != null): ?>
                <div class="col small-6 medium-3">
                    <a class="category_name" href="<?php echo $cat->getUrl(); ?>">
                       <img src="<?php echo $image; ?>" class="img-responsive category_image" alt="<?php echo $cat->getName(); ?>" />
                        <h2><?php echo $cat->getName(); ?></h2>
                    </a>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
        </div>
    </div>
</div>
